### ISSUE TITLE
Docstore API Responded with Non-Success Code: 301

### ISSUE THREAD

**Issue by m-gibson** [sharelatex/sharelatex-docker-image#103]
I'm having an issue trying to create projects within the ShareLatex Docker image. I can easily pull and run the image (even multiple versions for sanity checking) using the provided docker-compose file, set up an admin account, but cannot actually create a LaTeX project. Only difference is I'm using a separate Nginx container to act as a reverse proxy (no HTTPS whilst debugging this).

Every time I attempt to create some sort of project or file, I get the following errors in `web.log`.

```
{"name":"web-sharelatex","hostname":"latex.example.com","pid":116,"level":30,"req":{"url":"/project/5d1205520ad5e276004cab2e/compile?auto_compile=true","method":"POST","referrer":"http://latex.example.com/project/5d1205520ad5e276004cab2e","remote-addr":"10.215.147.187","user-agent":"Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36","content-length":"96"},"res":{"statusCode":500},"response-time":641,"msg":"http request","time":"2019-06-25T11:38:39.681Z","v":0}
{"name":"web-sharelatex","hostname":"latex.example.com","pid":116,"level":30,"user_id":"5d1205100ad5e276004cab2c","project_id":"5d1205520ad5e276004cab2e","msg":"allowing user write access to project content","time":"2019-06-25T11:38:56.494Z","v":0}
{"name":"main.tex","hostname":"latex.example.com","pid":116,"level":30,"project_id":"5d1205520ad5e276004cab2e","parent_folder_id":"5d1205520ad5e276004cab2d","msg":"getting request to add doc to project","time":"2019-06-25T11:38:56.494Z","v":0}
{"name":"web-sharelatex","hostname":"latex.example.com","pid":116,"level":30,"project_id":"5d1205520ad5e276004cab2e","folder_id":"5d1205520ad5e276004cab2d","docName":"main.tex","source":"editor","msg":"sending new doc to project","time":"2019-06-25T11:38:56.496Z","v":0}
{"name":"web-sharelatex","hostname":"latex.example.com","pid":116,"level":30,"project_id":"5d1205520ad5e276004cab2e","folder_id":"5d1205520ad5e276004cab2d","doc_name":"main.tex","msg":"adding doc to project with project","time":"2019-06-25T11:38:56.500Z","v":0}
{"name":"web-sharelatex","hostname":"latex.example.com","pid":116,"level":30,"folder_id":"5d1205520ad5e276004cab2d","project_id":"5d1205520ad5e276004cab2e","msg":"confirming folder in project","time":"2019-06-25T11:38:56.500Z","v":0}
{"name":"web-sharelatex","hostname":"latex.example.com","pid":116,"level":30,"project_id":"5d1205520ad5e276004cab2e","doc_id":"5d1207d00ad57a74001745e8","msg":"updating doc in docstore api","time":"2019-06-25T11:38:56.501Z","v":0}
{"name":"web-sharelatex","hostname":"latex.example.com","pid":116,"level":50,"err":{"message":"docstore api responded with non-success code: 301","name":"Error","stack":"Error: docstore api responded with non-success code: 301\n  at Request._callback (/var/www/sharelatex/web/app/js/Features/Docstore/DocstoreManager.js:194:19)\n  at Request.self.callback (/var/www/sharelatex/web/node_modules/request/request.js:188:22)\n  at Request.emit (events.js:98:17)\n  at Request.<anonymous> (/var/www/sharelatex/web/node_modules/request/request.js:1171:10)\n  at Request.emit (events.js:95:17)\n  at IncomingMessage.<anonymous> (/var/www/sharelatex/web/node_modules/request/request.js:1091:12)\n  at IncomingMessage.g (events.js:180:16)\n  at IncomingMessage.emit (events.js:117:20)\n  at _stream_readable.js:944:16\n  at process._tickDomainCallback (node.js:502:13)\n"},"project_id":"5d1205520ad5e276004cab2e","doc_id":"5d1207d00ad57a74001745e8","msg":"error updating doc in docstore","time":"2019-06-25T11:38:56.622Z","v":0}
{"name":"web-sharelatex","hostname":"latex.example.com","pid":116,"level":50,"err":{"message":"docstore api responded with non-success code: 301","name":"Error","stack":"Error: docstore api responded with non-success code: 301\n  at Request._callback (/var/www/sharelatex/web/app/js/Features/Docstore/DocstoreManager.js:194:19)\n  at Request.self.callback (/var/www/sharelatex/web/node_modules/request/request.js:188:22)\n  at Request.emit (events.js:98:17)\n  at Request.<anonymous> (/var/www/sharelatex/web/node_modules/request/request.js:1171:10)\n  at Request.emit (events.js:95:17)\n  at IncomingMessage.<anonymous> (/var/www/sharelatex/web/node_modules/request/request.js:1091:12)\n  at IncomingMessage.g (events.js:180:16)\n  at IncomingMessage.emit (events.js:117:20)\n  at _stream_readable.js:944:16\n  at process._tickDomainCallback (node.js:502:13)\n"},"project_id":"5d1205520ad5e276004cab2e","docName":"main.tex","msg":"error adding doc without lock","time":"2019-06-25T11:38:56.623Z","v":0}
{"name":"web-sharelatex","hostname":"latex.example.com","pid":116,"level":50,"err":{"message":"docstore api responded with non-success code: 301","name":"Error","stack":"Error: docstore api responded with non-success code: 301\n  at Request._callback (/var/www/sharelatex/web/app/js/Features/Docstore/DocstoreManager.js:194:19)\n  at Request.self.callback (/var/www/sharelatex/web/node_modules/request/request.js:188:22)\n  at Request.emit (events.js:98:17)\n  at Request.<anonymous> (/var/www/sharelatex/web/node_modules/request/request.js:1171:10)\n  at Request.emit (events.js:95:17)\n  at IncomingMessage.<anonymous> (/var/www/sharelatex/web/node_modules/request/request.js:1091:12)\n  at IncomingMessage.g (events.js:180:16)\n  at IncomingMessage.emit (events.js:117:20)\n  at _stream_readable.js:944:16\n  at process._tickDomainCallback (node.js:502:13)\n"},"url":"/project/5d1205520ad5e276004cab2e/doc","method":"POST","user":{"id":"5d1205100ad5e276004cab2c","email":"me@email.com"},"msg":"error passed to top level next middlewear","time":"2019-06-25T11:38:56.624Z","v":0}
{"name":"web-sharelatex","hostname":"latex.example.com","pid":116,"level":30,"req":{"url":"/project/5d1205520ad5e276004cab2e/doc","method":"POST","referrer":"http://latex.example.com/project/5d1205520ad5e276004cab2e","remote-addr":"10.215.147.187","user-agent":"Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36","content-length":"112"},"res":{"statusCode":500},"response-time":213,"msg":"http request","time":"2019-06-25T11:38:56.700Z","v":0}
```

The thing that sticks out at me the most is `error adding doc without lock`. Is this a redis or mongodb issue? I ran `check:mongo` and `check:redis` and they're reporting fine. Anything else I'm missing?

Should also note that I frequently get HTTP 500 errors when checking DevTools, for example `/compile` and `/doc`.

**Comment by isaiasfsilva** [comment]
Hello m-gibson, did you have news about your problem?

I'm having exactly the same problem. I'm using the docker image and everything is fine. I can create a new project (folders inside of the project), but when I try to create/upload a new file (does not matter its extension), I get the same error as you.

Did you solve your problem?

Any news from the community?

Thank you

**Comment by m-gibson** [comment]
> Hello m-gibson, did you have news about your problem?
> 
> I'm having exactly the same problem. I'm using the docker image and everything is fine. I can create a new project (folders inside of the project), but when I try to create/upload a new file (does not matter its extension), I get the same error as you.
> 
> Did you solve your problem?
> 
> Any news from the community?
> 
> Thank you

Hi isaiasfsilva,

To be honest I haven't looked into this again as it was taking too much time and I haven't heard anything else. I've tried out another Docker image for LaTeX called CoCalc (https://github.com/sagemathinc/cocalc-docker). Although it has a lot built in (I don't need a full data science suite), its LaTeX editor is working well.

**Comment by mserranom** [comment]
We’ve merged this repository into https://github.com/overleaf/overleaf, so we’re closing all of its issues and will archive it. If this is still a problem, please open a new issue on https://github.com/overleaf/overleaf . Thanks!
