### ISSUE TITLE
SQLITE_CANTOPEN: unable to open database file

### ISSUE THREAD

**Issue by ghost** [sharelatex/sharelatex-docker-image#24]
Hi there,

I am trying to run ShareLaTeX via LXC and followed all steps mentioned in the Dockerfile. But when I start all services I get the following error:

```
{"name":"clsi","hostname":"dbbf324cf0046ad","pid":15623,"level":30,"msg":"CLSI starting up, listening on localhost:3013","time":"2015-12-08T08:10:32.758Z","v":0}
Unhandled rejection SequelizeConnectionError: SQLITE_CANTOPEN: unable to open database file
    at Database.<anonymous> (/var/www/clsi/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:38:59)
```

I can register at localhost:3000 and open/create an example project but it doesn't compile:

```
{"name":"clsi","hostname":"dbbf324cf0046ad","pid":15623,"level":50,"err":{"message":"SQLITE_CANTOPEN: unable to open database file","name":"SequelizeConnectionError","stack":"SequelizeConnectionError: SQLITE_CANTOPEN: unable to open database file\n    at Database.<anonymous> (/var/www/clsi/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:38:59)","parent":{"errno":14,"code":"SQLITE_CANTOPEN"},"original":"[Circular]"},"msg":"server error","time":"2015-12-08T08:12:46.558Z","v":0}
{"name":"clsi","hostname":"dbbf324cf0046ad","pid":15623,"level":30,"req":{"url":"/project/56668720fdf03da00d27157b/compile","method":"POST","remote-addr":"127.0.0.1","content-length":"1391"},"res":{"statusCode":500},"response-time":5,"msg":"http request","time":"2015-12-08T08:12:46.561Z","v":0}
{"name":"web-sharelatex","hostname":"dbbf324cf0046ad","pid":15629,"level":50,"err":{"message":"CLSI returned non-success code: 500","name":"Error","stack":"Error: CLSI returned non-success code: 500\n  at Request._callback (/var/www/web/app/js/Features/Compile/ClsiManager.js:88:19)\n  at Request.self.callback (/var/www/web/node_modules/request/request.js:121:22)\n  at Request.emit (events.js:98:17)\n  at Request.<anonymous> (/var/www/web/node_modules/request/request.js:978:14)\n  at Request.emit (events.js:117:20)\n  at IncomingMessage.<anonymous> (/var/www/web/node_modules/request/request.js:929:12)\n  at IncomingMessage.emit (events.js:117:20)\n  at _stream_readable.js:944:16\n  at process._tickDomainCallback (node.js:492:13)\n"},"project_id":"56668720fdf03da00d27157b","msg":"CLSI returned failure code","time":"2015-12-08T08:12:46.564Z","v":0}
{"name":"web-sharelatex","hostname":"dbbf324cf0046ad","pid":15629,"level":50,"err":{"message":"CLSI returned non-success code: 500","name":"Error","stack":"Error: CLSI returned non-success code: 500\n  at Request._callback (/var/www/web/app/js/Features/Compile/ClsiManager.js:88:19)\n  at Request.self.callback (/var/www/web/node_modules/request/request.js:121:22)\n  at Request.emit (events.js:98:17)\n  at Request.<anonymous> (/var/www/web/node_modules/request/request.js:978:14)\n  at Request.emit (events.js:117:20)\n  at IncomingMessage.<anonymous> (/var/www/web/node_modules/request/request.js:929:12)\n  at IncomingMessage.emit (events.js:117:20)\n  at _stream_readable.js:944:16\n  at process._tickDomainCallback (node.js:492:13)\n"},"url":"/project/56668720fdf03da00d27157b/compile","method":"POST","msg":"error passed to top level next middlewear","time":"2015-12-08T08:12:46.564Z","v":0}
{"name":"web-sharelatex","hostname":"dbbf324cf0046ad","pid":15629,"level":30,"req":{"url":"/project/56668720fdf03da00d27157b/compile","method":"POST","referrer":"http://localhost:3000/project/56668720fdf03da00d27157b","remote-addr":"127.0.0.1","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/45.0.2454.101 Chrome/45.0.2454.101 Safari/537.36","content-length":"88"},"res":{"statusCode":500},"response-time":61,"msg":"http request","time":"2015-12-08T08:12:46.566Z","v":0}
```

**Comment by dpasqualin** [comment]
I'm trying to use Docker image 0.2.0 and I'm having a similar issue.

```
[2016-01-25T16:33:11.516Z] ERROR: clsi/87 on 5b8a50b0e7ab: server error (err.original=[Circular])
    SequelizeDatabaseError: SQLITE_READONLY: attempt to write a readonly database
        at module.exports.Query.formatError (/var/www/sharelatex/clsi/node_modules/sequelize/lib/dialects/sqlite/query.js:239:16)
        at Statement.<anonymous> (/var/www/sharelatex/clsi/node_modules/sequelize/lib/dialects/sqlite/query.js:47:31)
        at Statement.replacement (/var/www/sharelatex/clsi/node_modules/sqlite3/lib/trace.js:20:31)
```

**Comment by mserranom** [comment]
We’ve merged this repository into https://github.com/overleaf/overleaf, so we’re closing all of its issues and will archive it. If this is still a problem, please open a new issue on https://github.com/overleaf/overleaf . Thanks!
