### ISSUE TITLE
Error: CERT_UNTRUSTED on user invite

### ISSUE THREAD

**Issue by fleimgruber** [sharelatex/sharelatex-docker-image#58]
For reference, the run command used:

```
docker run -d  -v ~/sharelatex_data:/var/lib/sharelatex  -p 5001:80  --name=sharelatex_latest  --env SHARELATEX_EMAIL_SMTP_HOST=some.ip.to.smtp  --env SHARELATEX_EMAIL_FROM_ADDRESS=sharelatex.support@our.domain  --env SHARELATEX_EMAIL_SMTP_PORT=25  --env SHARELATEX_EMAIL_SMTP_SECURE=false  --env SHARELATEX_EMAIL_SMTP_IGNORE_TLS=true  --env SHARELATEX_EMAIL_SMTP_TLS_REJECT_UNAUTH=false some/label:sharelatex_latest
```

When inviting a user from the "Share Project" form, I get the following error in the `web.log`.

```
{"name":"web-sharelatex","hostname":"80e4963b4f6c","pid":1133,"level":30,"req":{"url":"/user/contacts","method":"GET","referrer":"http://our.sharelatex:5001/project/57ff90f1a0a95d5d009c10a4","remote-addr":"127.0.0.1","user-agent":"Mozilla/5
.0 (Windows NT 6.1; WOW64; rv:48.0) Gecko/20100101 Firefox/48.0"},"res":{"statusCode":500},"response-time":486,"msg":"http request","time":"2016-10-14T07:31:27.320Z","v":0}
{"name":"web-sharelatex","hostname":"80e4963b4f6c","pid":1133,"level":30,"user_id":"57a8876d64104aa400a26ead","project_id":"57ff90f1a0a95d5d009c10a4","msg":"allowing user admin access to project","time":"2016-10-14T07:31:28.244Z","v":0
}
{"name":"web-sharelatex","hostname":"80e4963b4f6c","pid":1133,"level":30,"projectId":"57ff90f1a0a95d5d009c10a4","inviteId":"57ffaa9ca0a95d5d009c10a9","msg":"resending invite","time":"2016-10-14T07:31:28.244Z","v":0}
{"name":"web-sharelatex","hostname":"80e4963b4f6c","pid":1133,"level":30,"projectId":"57ff90f1a0a95d5d009c10a4","inviteId":"57ffaa9ca0a95d5d009c10a9","msg":"resending invite email","time":"2016-10-14T07:31:28.245Z","v":0}
{"name":"web-sharelatex","hostname":"80e4963b4f6c","pid":1133,"level":30,"projectId":"57ff90f1a0a95d5d009c10a4","inviteId":"57ffaa9ca0a95d5d009c10a9","msg":"sending notification and email for invite","time":"2016-10-14T07:31:28.251Z","
v":0}
{"name":"web-sharelatex","hostname":"80e4963b4f6c","pid":1133,"level":30,"receiver":"some.user@our.domain","subject":"project1 - shared by some.other.user@our.domain","msg":"sending email","time":"2016-10-14T07:31:28.274Z","v
":0}
{"name":"web-sharelatex","hostname":"80e4963b4f6c","pid":1133,"level":50,"err":{"message":"CERT_UNTRUSTED","name":"Error","stack":"Error: CERT_UNTRUSTED\n  at SecurePair.<anonymous> (tls.js:1381:32)\n  at SecurePair.emit (events.js:92:
17)\n  at SecurePair.maybeInitFinished (tls.js:980:10)\n  at CleartextStream.read [as _read] (tls.js:472:13)\n  at CleartextStream.Readable.read (_stream_readable.js:341:10)\n  at EncryptedStream.write [as _write] (tls.js:369:25)\n  at
 doWrite (_stream_writable.js:226:10)\n  at writeOrBuffer (_stream_writable.js:216:5)\n  at EncryptedStream.Writable.write (_stream_writable.js:183:11)\n  at Socket.ondata (stream.js:51:26)\n  at Socket.emit (events.js:95:17)\n  at Soc
ket.<anonymous> (_stream_readable.js:765:14)\n  at Socket.emit (events.js:92:17)\n  at emitReadable_ (_stream_readable.js:427:10)\n  at emitReadable (_stream_readable.js:423:5)\n  at readableAddChunk (_stream_readable.js:166:9)\n  at S
ocket.Readable.push (_stream_readable.js:128:10)\n  at TCP.onread (net.js:529:21)\n"},"msg":"error sending message","time":"2016-10-14T07:31:28.367Z","v":0}
```

I already tried

```
npm config set strict-ssl false
npm config set ca null
```

as per some comments found by searching for `CERT_UNTRUSTED`.  Since we are in a safe LAN.  Any hints?

**Comment by djwf** [comment]
Check out the pull request I recently added for web-sharelatex (https://github.com/sharelatex/web-sharelatex/pull/361), it solved a similar problem I was having (where people could not reset their passwords).  As currently coded, nodemailer doesn't get the ignoreTLS setting, my patch fixes that problem.

You'll also need to recompile the coffee scripts if you're applying this to a running installation.

**Comment by fleimgruber** [comment]
@djwf resolved using latest changes from master.
