### ISSUE TITLE
Request validation needed

### ISSUE THREAD

**Issue by Morilor** [sharelatex/sharelatex-docker-image#99]
There _is_ a request validation on http request, but in `server/__init__.py`, line 142: 
`client, msg, req_id, msg_len = request`
we use anything that comes from frontend.recv_multipart(). It's not a problem unless there is a malicious request posted directly into zmq. [Mirai worm](https://fortiguard.com/encyclopedia/virus/7244913) is capable of doing exactly that, resulting in this error message:

```
E:VENTILATOR:[__i:_ru:141]:received a wrongly-formatted request (expected 4 frames, got 1)
E:VENTILATOR:[__i:_ru:142]:field 0: b'ing: gzip, deflate\r\nAccept: */*\r\nUser-Agent: python-requests/2.12.4\r\nSOAPAction: urn:dslforum-org:service:Time'
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/bert_serving/server/__init__.py", line 139, in _run
    client, msg, req_id, msg_len = request
ValueError: not enough values to unpack (expected 4, got 1)
E:VENTILATOR:[__i:_ru:141]:received a wrongly-formatted request (expected 4 frames, got 2)
E:VENTILATOR:[__i:_ru:142]:field 0: b'#SetNTPServers\r\nContent-Length: 538\r\n\r\n\r\n<?xml version="1'
field 1: b'"\r\n<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://'
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/bert_serving/server/__init__.py", line 139, in _run
    client, msg, req_id, msg_len = request
ValueError: not enough values to unpack (expected 4, got 2)
I:PROXY:[htt:enc: 47]:new request from 91.191.250.154
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.5/dist-packages/bert_serving/server/__init__.py", line 92, in run
    self._run()
  File "/usr/local/lib/python3.5/dist-packages/zmq/decorators.py", line 75, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/zmq/decorators.py", line 75, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/zmq/decorators.py", line 75, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/bert_serving/server/zmq_decor.py", line 27, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/bert_serving/server/__init__.py", line 144, in _run
    server_status.update(request)
  File "/usr/local/lib/python3.5/dist-packages/bert_serving/server/__init__.py", line 542, in update
    self._hist_msg_len[int(msg_len)] += 1
ValueError: invalid literal for int() with base 10: b'.147/d; sh d`</NewNTPServer1>\r\n   <NewNTPServer2></N'
```
client, msg, req_id, msg_len need to be checked at least for bytes type and that req_id, msg_len are int convertable. As a temporary solution I just added two lines
```
int(req_id)
int(msg_len)
```
after their initialisation under "try". Since ValueError is raised if bytes can't be converted to int, already existing "except ValueError" works fine.

**Comment by mserranom** [comment]
We’ve merged this repository into https://github.com/overleaf/overleaf, so we’re closing all of its issues and will archive it. If this is still a problem, please open a new issue on https://github.com/overleaf/overleaf . Thanks!
